spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marjo-pay
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: appfile.log

jwt:
  expiracao: 30
  chave-assinatura: YSBsZWJyZSDDqSBicmFuY2E=

management:
  endpoints:
    web:
      exposure:
        include: "*"
